# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-28 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eggs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('payEmail', models.EmailField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('eggs', models.CharField(choices=[('eggCount1', 50), ('eggCount2', 100)], max_length=2)),
            ],
        ),
    ]
