# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggform', '0002_auto_20180128_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggs',
            name='eggs',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='number',
            field=models.IntegerField(max_length=10),
        ),
    ]
